### ISSUE TITLE
Question about `copilot_thread_id`

### ISSUE THREAD

**Issue by naruto3315** [copilot-extensions/preview-sdk.js#116]
I just build a copilot extension based on this sdk. However, I found that the `copilot_thread_id` field seems to have different meanings on different platforms. In VSCode, it is the same within the same conversation. In Visual Studio, its value is different for two messages in the same conversation. In PyCharm, its value is an empty string. Should this field have a consistent definition across all IDEs?

**Comment by gr2m** [comment]
Can you share what you found out? I'm curious
