### ISSUE TITLE
Python sample?

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [copilot-extensions/preview-sdk.js#117]
This SDK would be valuable, except I really need to write my GitHub Copilot Extension in python. Is there a way to do that using code from this SDK as a wrapper? Or is anyone aware of a repo with a simple python example of a GitHub Copilot Extension? Thanks.

**Comment by gr2m** [comment]
Hmm I don't know of any work towards an SDK written in Python, but I'll ask!

Worst case look at the functionality you need and just re-write it in Python. There is fairly little code at this point, the code and its tests should be a good reference to get started

**Comment by rickyloynd-microsoft** [comment]
Yes, an entire SDK would be asking for a lot. I would be happy with a single running example in python.

**Comment by rickyloynd-microsoft** [comment]
Well, I asked ChatGPT to convert the index.js file from the blackbeard sample to python, and its code worked fine using flask.
