### ISSUE TITLE
Parse requests from Copilot

### ISSUE THREAD

**Issue by gr2m** [copilot-extensions/preview-sdk.js#13]
Implement a method for parsing incoming requests (from Copilot).

Two reasons

1. Getting type intellisense for the shape of the request
2. Removing Copilot specific keys that cause OpenAI trouble ([example](https://github.com/jclem/hacker-agent/blob/096748a870824055da56c784fad8228d58f20452/index.ts#L29-L32))

So maybe it should be two low-level methods. The high-level SDK should do the parsing implicitly and give full type intellisense. And ideally would do the payload clean up transparently as well when passing to a model API other than CAPI.

### Example

```js
// `requestBody` can be either a JSON string or an object
const input = parseRequest(requestBody);
// `input` now has full TypeIntellisense

// pass through any input properties safely to OpenAI
const inputCompat = removeCopilotKeysFromRequest(input);
const stream = openai.beta.chat.completions.stream({
  messages: [systemMessage, ...input.data.messages],
  model: "gpt-4-1106-preview",
  stream: true,
});
```

**Comment by alexisabril** [comment]
I'm definitely in favor of the ability to type an incoming request shape. I'm agnostic, but not opposed, to the `removeCopilotKeysFromRequest` method as we may continue to add properties to the incoming request object. As a result, this method may need to have a higher level of upkeep and may be considered coupled (a bit) to OpenAI. For instance, Anthropic may consider the entire shape to be invalid, rendering this translation method moot.

`verifyAndParse` having a potential avenue across other APIs brings value to replicating this pattern here. For me personally, I'm a fan of two separate methods that can be composed:

```
verify(parse)(req)
```

The only thought to keeping the separate I have is if the consumer chooses an architecture where verification happens earlier and separately from any additional request handling.

**Comment by gr2m** [comment]
good point on making `removeCopilotKeysFromRequest` specific to OpenAI, I think we should do that.

**Comment by gr2m** [comment]
I added one more issue

- https://github.com/copilot-extensions/preview-sdk.js/issues/33

I'm sure a similar function would be useful for function calling, but I get there when I get there. I need to experiment more with
