### ISSUE TITLE
Bug: `README.md` points to a non-existent `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by francisfuzz** [copilot-extensions/preview-sdk.js#67]
## Summary

The `README.md` points to a non-existent `CONTRIBUTING.md` at `.github/CONTRIBUTING.md`.

However, there _is_ a `CONTRIBUTING.md` in the root of the repository. 😉

**Comment by francisfuzz** [comment]
⛳ Tee'd up: https://github.com/copilot-extensions/preview-sdk.js/pull/66

**Comment by gr2m** [comment]
done via #66
