### ISSUE TITLE
Unable to run `npm test` on fresh Codespace

### ISSUE THREAD

**Issue by francisfuzz** [copilot-extensions/preview-sdk.js#68]
## Summary

Hi Copilot team! I am interested in contributing to this repository. However, I am unable to run tests on fresh Codespace.

Steps to reproduce the issue:

- Create a new Codespace from default branch (at time of writing: https://github.com/copilot-extensions/preview-sdk.js/commit/8c434bce3034752be8dd586645e8e9fce46e0b82)
- Run `npm test`

### Expected

Tests run and pass!

### Actual

Test scripts are run, but `node` tells me I have a "bad option":

```shell
@francisfuzz ➜ /workspaces/preview-sdk.js (main) $ npm test

> @copilot-extensions/preview-sdk@0.0.0-development test
> npm run test:code && npm run test:tsc && npm run test:types


> @copilot-extensions/preview-sdk@0.0.0-development test:code
> node --test --experimental-test-coverage --experimental-test-snapshots

node: bad option: --experimental-test-snapshots
```

Looking at the Node docs, it seems like [this flag](https://nodejs.org/api/cli.html#--experimental-test-snapshots) was introduced in `v22.3.0`.

However, checking Codespaces, I see that the installed Node version is behind:

```shell
@francisfuzz ➜ /workspaces/preview-sdk.js (main) $ node -v
v20.16.0
```

Would addressing this solely be a matter of having `v22.x.x`+ as a pinned node version? 💭

**Comment by francisfuzz** [comment]
I cut #71 as a first pass at addressing this!

**Comment by gr2m** [comment]
> I cut [#71](https://github.com/copilot-extensions/preview-sdk.js/pull/71) as a first pass at addressing this!

thank you, that's great!

I also created an issue to eventually move away from using the Node APIs that require v22: #73
