### ISSUE TITLE
Issue and pull request templates: should we have them?

### ISSUE THREAD

**Issue by francisfuzz** [copilot-extensions/preview-sdk.js#80]
## Summary

Straight from the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates):

> With issue and pull request templates, you can customize and standardize the information you'd like contributors to include when they open issues and pull requests in your repository.

I'm not sure if there's an existing canon we can pull from in this organization or in the `github` organization, but maybe something to consider for the future? 🤔

**Comment by gr2m** [comment]
I feel it's a bit early for pull request templates, I think they can be a great help to help maintain a project, but cause friction for contributors, especially if they are not a good fit. If you would like to try, I'd start with something very minimal.

**Comment by francisfuzz** [comment]
Sure! How does this draft look/feel?

```markdown
### What are you trying to accomplish?

### What approach did you choose and why?

### What should reviewers focus on?
```

**Comment by gr2m** [comment]
sounds like a great start 👍🏼 maybe we could add an HTML comment stating that these are just suggestions and contributors can change or remove headers if they don't fit their use case?
