### ISSUE TITLE
Bring test coverage to 100%

### ISSUE THREAD

**Issue by gr2m** [copilot-extensions/preview-sdk.js#87]
Now that we have test coverage enabled via #86 thanks to @artifactz1, we can address the parts of the code that are not yet covered and do so. Where applicable, lines or branches can also be ignored, see [syntax](https://github.com/bcoe/c8/blob/main/README.md#ignoring-uncovered-lines-functions-and-blocks)

**Comment by oscard0m** [comment]
I'm working on this!

- [ ] https://github.com/copilot-extensions/preview-sdk.js/pull/100
- [ ] Improve coverage for `prompt.js`
- [ ] Improve coverage for `verification.js`

**Comment by gr2m** [comment]
yoooo @oscard0m so nice to see you contribute ❤
