### ISSUE TITLE
Add npm script to create coverage report

### ISSUE THREAD

**Issue by gr2m** [copilot-extensions/preview-sdk.js#88]
Here is what I like to do:

https://github.com/gr2m/github-project/blob/7b3bd05b4fc100fec355d03ac6d71de5cb9a0257/package.json#L15-L16

It requires `open-cli` as a new dev dependency

**Comment by oscard0m** [comment]
@gr2m should we close this issue? It was solved by https://github.com/copilot-extensions/preview-sdk.js/pull/102, right?

**Comment by gr2m** [comment]
it is, thanks @oscard0m!
